version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: sanik
      POSTGRES_PASSWORD: sanikpw
      POSTGRES_DB: sanikdb
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
